// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBHY_W0jX63_znQTeZvSXyzNKWZy2PenoI',
    appId: '1:1080667953835:web:eedd8f29ac18b6fa2275ee',
    messagingSenderId: '1080667953835',
    projectId: 'shopapp-8c208',
    authDomain: 'shopapp-8c208.firebaseapp.com',
    storageBucket: 'shopapp-8c208.firebasestorage.app',
    measurementId: 'G-PS44HSXG7Z',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCqyOAauZsLdc2td0OyY8S9JM9LFXOGqvQ',
    appId: '1:1080667953835:android:045ef138e83bbbd02275ee',
    messagingSenderId: '1080667953835',
    projectId: 'shopapp-8c208',
    storageBucket: 'shopapp-8c208.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDMZA48UrdTLOs-237-gJU-AUZjJxf3uiU',
    appId: '1:1080667953835:ios:43860d794f9789b22275ee',
    messagingSenderId: '1080667953835',
    projectId: 'shopapp-8c208',
    storageBucket: 'shopapp-8c208.firebasestorage.app',
    iosBundleId: 'com.example.eCom',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDMZA48UrdTLOs-237-gJU-AUZjJxf3uiU',
    appId: '1:1080667953835:ios:43860d794f9789b22275ee',
    messagingSenderId: '1080667953835',
    projectId: 'shopapp-8c208',
    storageBucket: 'shopapp-8c208.firebasestorage.app',
    iosBundleId: 'com.example.eCom',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBHY_W0jX63_znQTeZvSXyzNKWZy2PenoI',
    appId: '1:1080667953835:web:27262576546a21472275ee',
    messagingSenderId: '1080667953835',
    projectId: 'shopapp-8c208',
    authDomain: 'shopapp-8c208.firebaseapp.com',
    storageBucket: 'shopapp-8c208.firebasestorage.app',
    measurementId: 'G-YYJZ2WMBFK',
  );
}
